<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aim_arm_hardware</name>
  <version>0.1.0</version>
  <description>Serial hardware bridge for sending AIM-RL joint commands to a microcontroller.</description>
  <maintainer email="paneendrakumar0@example.com">Paneendra Kumar</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>trajectory_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

